import mysql from 'mysql2/promise';import {readFileSync} from 'node:fs';import {createReportsModule} from '../modules/reports/index.js';import {createPreviewReadAuthorization} from '../middleware/preview-read-auth.js';import {serializePreviewCall} from '../modules/customer-history/preview-adapters.js';
export async function createPreviewReports(){const config=JSON.parse(readFileSync(new URL('../.private/customer-history-db.json',import.meta.url),'utf8'));const db=mysql.createPool({...config,connectionLimit:2});
 const rowsFor=async({date,agentId=''})=>{const params=[date];let agent='';if(agentId){agent=' AND agent_id=?';params.push(agentId);}const [rows]=await db.query(`SELECT * FROM attica_calls WHERE call_date=?${agent} ORDER BY created_at DESC`,params);return rows;};
 const summarize=rows=>{const incoming=rows.filter(r=>r.direction==='incoming'),outgoing=rows.filter(r=>r.direction==='outgoing'),answered=rows.filter(r=>Number(r.talkDurationSeconds)>0||r.status==='completed');return {total:rows.length,inbound:incoming.length,outbound:outgoing.length,answered:answered.length,missed:rows.length-answered.length,incomingTotal:incoming.length,incomingAnswered:incoming.filter(r=>Number(r.talkDurationSeconds)>0).length,incomingMissed:incoming.filter(r=>!Number(r.talkDurationSeconds)).length,incomingUnique:new Set(incoming.map(r=>r.callerId)).size,outgoingTotal:outgoing.length,outgoingDialed:outgoing.length,outgoingAnswered:outgoing.filter(r=>Number(r.talkDurationSeconds)>0).length,outgoingUnique:new Set(outgoing.map(r=>r.callerId)).size,outgoingUniqueAnswered:new Set(outgoing.filter(r=>Number(r.talkDurationSeconds)>0).map(r=>r.callerId)).size,followUpTotal:0,followUpDialed:0,followUpAnswered:0,followUpUnique:0,followUpUniqueAnswered:0};};
 const serializeRows=async rows=>rows.map(serializePreviewCall);const filteredRows=async filters=>{const start=filters.date||filters.fromDate||'0000-01-01',end=filters.date||filters.toDate||'9999-12-31';const [rows]=await db.query('SELECT * FROM attica_calls WHERE call_date>=? AND call_date<=? ORDER BY created_at DESC',[start,end]);return (await serializeRows(rows)).filter(row=>(!filters.agentId||row.agentId===filters.agentId)&&(!filters.direction||row.direction===filters.direction)&&(!filters.status||row.status===filters.status)&&(!filters.language||row.language===filters.language)&&(!filters.branch||row.branch===filters.branch));};
 const hourly=async filters=>{const rows=await filteredRows(filters);return Array.from({length:24},(_,hour)=>({hour,total:rows.filter(row=>Number(String(row.time||'').slice(0,2))===hour).length}));};
 const cache=new Map();const adapters={businessDate:()=> '2026-09-20',dateRows:rowsFor,serializeRows,summarizeRows:summarize,
 dashboardSummary:async date=>summarize(await serializeRows(await rowsFor({date}))),queueMetrics:async()=>({outgoingQueue:0,followUpQueue:0}),hourly,
 summaryCache:cache,summaryCacheTtl:30000,summaryCacheKey:filters=>JSON.stringify(filters),readSharedSummary:()=>null,writeSharedSummary:()=>{},
 normalizeDisposition:value=>String(value||'').trim().toLowerCase(),normalizeSource:value=>String(value||'').trim().toLowerCase(),filteredRows,
 filteredSummary:async filters=>summarize(await filteredRows(filters)),filteredHourly:hourly,filteredBreakdowns:async()=>({branches:[],languages:[],statuses:[]}),
 buildAnalytics:(rows)=>({summary:summarize(rows),hourly:[],branches:[],languages:[],statuses:[],rowCount:rows.length,maxRows:0}),
 maxListLimit:100,defaultListLimit:50,compactRows:rows=>rows,databaseList:async({filters,page,limit})=>{const rows=await filteredRows(filters),total=rows.length,offset=(page-1)*limit;return {page,limit,total,totalPages:total?Math.ceil(total/limit):0,summary:summarize(rows),results:rows.slice(offset,offset+limit)};},
 exportCsv:async({filters,res})=>{const rows=await filteredRows(filters);res.set({'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="attica-report-${filters.date||filters.fromDate}-to-${filters.date||filters.toDate}.csv"`,'X-Report-Row-Count':String(rows.length),'X-Report-Max-Rows':'0'});res.end('\uFEFFCall ID,Phone,Direction,Agent,Date,Time\r\n'+rows.map(row=>[row.id,row.callerId,row.direction,row.agentId,row.date,row.time].map(value=>`"${String(value||'').replaceAll('"','""')}"`).join(',')).join('\r\n')+'\r\n');}};
 const actors=JSON.parse(readFileSync(new URL('../.private/message-actors.json',import.meta.url),'utf8'));return {...createReportsModule(adapters),authorize:createPreviewReadAuthorization(actors),close:()=>db.end()};}
