import mysql from'mysql2/promise';import{readFileSync}from'node:fs';import{createIntakeModule}from'../modules/intake/index.js';import{createPreviewReadAuthorization}from'../middleware/preview-read-auth.js';
const present=row=>row?{callId:row.call_id,intakeToken:row.intake_token,agentId:row.agent_id,revision:Number(row.draft_revision),confirmedEndedAt:row.confirmed_ended_at?new Date(row.confirmed_ended_at).toISOString():null,dispositionSelectedAt:row.disposition_selected_at?new Date(row.disposition_selected_at).toISOString():null,autoSubmitAt:null,submittedAt:row.finalized_at?new Date(row.finalized_at).toISOString():null,submissionMethod:row.submission_method,requiresReview:JSON.parse(row.review_reasons||'[]'),pendingServerSave:Boolean(row.last_error),draft:JSON.parse(row.draft_json||'{}'),serverNow:new Date().toISOString()}:null;
export async function createPreviewIntake(){const config=JSON.parse(readFileSync(new URL('../.private/intake-preview-db.json',import.meta.url),'utf8'));if(config.host!=='127.0.0.1'||config.database!=='attica_next_intake'||config.user!=='attica_intake_preview')throw new Error('Intake requires isolated staging database');const db=mysql.createPool({...config,connectionLimit:2,multipleStatements:false});await db.query('SELECT 1');
 const adapters={
  saveForm:async body=>{const callId=String(body.id||body.callId||'').trim();if(!callId)return{};const token=String(body.intakeToken||`INTAKE-${callId}`);await db.query("INSERT INTO attica_intake_forms (call_id,intake_token,normalized_phone,customer_name,agent_id,agent_name,language,business_type,purpose,notes,submission_status,last_saved_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE customer_name=VALUES(customer_name),language=VALUES(language),business_type=VALUES(business_type),purpose=VALUES(purpose),notes=VALUES(notes),last_saved_at=UTC_TIMESTAMP(3)",[callId,token,String(body.callerId||''),String(body.customerName||''),String(body.agentId||''),String(body.agentName||''),String(body.language||''),String(body.businessType||''),String(body.purpose||''),String(body.notes||''),'Draft']);return{...body,callId,intakeToken:token,normalizedPhone:String(body.callerId||''),lastSavedAt:new Date()};},
  syncIvr:async()=>{},customerIdForPhone:p=>p?`TEST-${p.slice(-4)}`:'',toIso:v=>v?new Date(v).toISOString():null,
  readPending:async agentId=>{const [rows]=await db.query('SELECT * FROM attica_intake_workflows WHERE agent_id=? AND finalized_at IS NULL AND confirmed_ended_at IS NOT NULL ORDER BY created_at,call_id LIMIT 1',[agentId]);return present(rows[0]);},
  pendingCall:async workflow=>{const [rows]=await db.query('SELECT id,status,agent_id AS agentId FROM attica_calls WHERE id=? AND agent_id=? LIMIT 1',[workflow.callId,workflow.agentId]);return rows[0]||null;},
  readWorkflow:async(callId,agentId)=>{const [rows]=await db.query('SELECT * FROM attica_intake_workflows WHERE call_id=? AND agent_id=? LIMIT 1',[callId,agentId]);return present(rows[0]);},
  mutateWorkflow:async value=>{if(!['draft','submit'].includes(value.action))throw Object.assign(new Error('Invalid intake action'),{statusCode:400});const connection=await db.getConnection();try{await connection.beginTransaction();const [rows]=await connection.query('SELECT * FROM attica_intake_workflows WHERE call_id=? FOR UPDATE',[value.callId]);const row=rows[0];if(!row||row.agent_id!==value.agentId||row.intake_token!==value.intakeToken)throw Object.assign(new Error('Intake session does not match'),{statusCode:403});if(Number(value.revision)!==Number(row.draft_revision))throw Object.assign(new Error('Draft revision changed. Reload the saved draft and retry.'),{statusCode:409});const draft=JSON.stringify({...value.draft,id:row.call_id,callUuid:row.call_id,intakeToken:row.intake_token,agentId:row.agent_id});const revision=Number(row.draft_revision)+1,finalized=value.action==='submit'?new Date():null;await connection.query('UPDATE attica_intake_workflows SET draft_json=?,draft_revision=?,finalized_at=COALESCE(finalized_at,?),submission_method=CASE WHEN ? IS NULL THEN submission_method ELSE \'manual\' END,auto_submit_at=NULL,last_error=NULL WHERE call_id=?',[draft,revision,finalized,finalized,row.call_id]);await connection.query("UPDATE attica_intake_forms SET customer_name=?,notes=?,submission_status=?,submitted_at=?,submission_method=? ,last_saved_at=UTC_TIMESTAMP(3) WHERE call_id=?",[String(value.draft?.customerName||''),String(value.draft?.notes||''),finalized?'Submitted':'Draft',finalized,finalized?'manual':null,row.call_id]);await connection.commit();const [updated]=await db.query('SELECT * FROM attica_intake_workflows WHERE call_id=?',[row.call_id]);return present(updated[0]);}catch(e){await connection.rollback();throw e;}finally{connection.release();}},
  isRetryable:e=>['ER_LOCK_DEADLOCK','ER_LOCK_WAIT_TIMEOUT'].includes(e?.code),normalizeAgentId:v=>String(v||'').trim().toUpperCase().slice(0,20),cleanCallId:v=>String(v||'').trim().slice(0,120),cleanErrorCode:v=>String(v||'').trim().slice(0,80),
 };
 const actors=JSON.parse(readFileSync(new URL('../.private/message-actors.json',import.meta.url),'utf8'));return{...createIntakeModule(adapters),authorize:createPreviewReadAuthorization(actors),reset:async()=>{await db.query("UPDATE attica_intake_workflows SET draft_json='{}',draft_revision=0,finalized_at=NULL,submission_method=NULL,last_error=NULL,auto_submit_at=NULL WHERE call_id='TEST-INTAKE-CALL'");await db.query("UPDATE attica_intake_forms SET customer_name='',notes='',submission_status='Draft',submitted_at=NULL,submission_method=NULL WHERE call_id='TEST-INTAKE-CALL'");},close:()=>db.end()};}
