import test from 'node:test';import assert from 'node:assert/strict';import {createReportsModule} from './index.js';
function fixture(overrides={}){const rows=[{direction:'incoming',callerId:'1',status:'completed',leadSource:'Incoming'},{direction:'outgoing',callerId:'2',status:'missed',leadSource:'Google'}];const summary={total:2,inbound:1,outbound:1,answered:1,missed:1,incomingTotal:1,incomingAnswered:1,incomingMissed:0,incomingUnique:1,outgoingTotal:1,outgoingDialed:1,outgoingAnswered:0,outgoingUnique:1,outgoingUniqueAnswered:0,followUpTotal:0,followUpDialed:0,followUpAnswered:0,followUpUnique:0,followUpUniqueAnswered:0};let seen;const module=createReportsModule({businessDate:()=> '2026-09-20',dashboardSummary:async()=>summary,queueMetrics:async()=>({outgoingQueue:3,followUpQueue:4}),hourly:async q=>(seen=q,[{hour:10,total:2}]),dateRows:async q=>(seen=q,rows),serializeRows:async r=>r,summarizeRows:()=>summary,
summaryCache:new Map(),summaryCacheTtl:30000,summaryCacheKey:f=>JSON.stringify(f),readSharedSummary:()=>null,writeSharedSummary:()=>{},normalizeDisposition:v=>String(v||'').toLowerCase(),normalizeSource:v=>String(v||'').toLowerCase(),filteredRows:async()=>rows,filteredSummary:async()=>summary,filteredHourly:async()=>[{hour:10,total:2}],filteredBreakdowns:async()=>({branches:['A']}),buildAnalytics:r=>({summary:{total:r.length},hourly:[],rowCount:r.length,maxRows:0}),maxListLimit:100,defaultListLimit:50,compactRows:r=>r,databaseList:async({page,limit})=>({page,limit,total:2,totalPages:1,summary,results:rows}),exportCsv:async value=>{seen=value;},...overrides});return {module,get seen(){return seen;}};}
test('stats preserves dashboard and queue response shape',async()=>{const {module}=fixture();const value=await module.service.stats();assert.equal(value.total,2);assert.equal(value.outgoingQueue,3);assert.equal(value.followUpQueue,4);assert.deepEqual(value.hourly,[{hour:10,total:2}]);});
test('date details validates required date with legacy payload',async()=>{const {module}=fixture();await assert.rejects(module.service.dateDetails({}),e=>e.status===400&&e.payload.error==='date required');});
test('date details rejects impossible date',async()=>{const {module}=fixture();await assert.rejects(module.service.dateDetails({date:'2026-02-30'}),e=>e.status===400);});
test('date details normalizes agent and repeats summary at top level',async()=>{const value=fixture();const result=await value.module.service.dateDetails({date:'2026-09-20',agentId:' test_in '});assert.deepEqual(value.seen,{date:'2026-09-20',agentId:'TEST_IN'});assert.equal(result.total,2);assert.deepEqual(result.summary.total,2);assert.equal(result.results.length,2);});
test('missing report adapter is rejected',()=>assert.throws(()=>createReportsModule({}),/adapter missing/));
test('report summary requires a date range',async()=>{const {module}=fixture();await assert.rejects(module.service.reportSummary({}),e=>e.status===400&&e.message.includes('date'));});
test('report summary rejects reversed range',async()=>{const {module}=fixture();await assert.rejects(module.service.reportSummary({fromDate:'2026-09-21',toDate:'2026-09-20'}),e=>e.status===400);});
test('report summary uses full database aggregates when no source/disposition is selected',async()=>{const {module}=fixture();const result=await module.service.reportSummary({date:'2026-09-20'});assert.equal(result.summary.total,2);assert.deepEqual(result.branches,['A']);assert.equal(result.rowCount,2);assert.equal(result.maxRows,0);});
test('report summary filters source across the full fetched population',async()=>{const {module}=fixture();const result=await module.service.reportSummary({date:'2026-09-20',source:'Google'});assert.equal(result.summary.total,1);assert.equal(result.rowCount,1);});
test('report summary shares in-flight cache work',async()=>{let calls=0;const value=fixture({filteredSummary:async()=>{calls++;await new Promise(r=>setTimeout(r,5));return {total:2};}});const [a,b]=await Promise.all([value.module.service.reportSummary({date:'2026-09-20'}),value.module.service.reportSummary({date:'2026-09-20'})]);assert.equal(calls,1);assert.deepEqual(a,b);});
test('call list applies safe page sizes and delegates unfiltered pagination',async()=>{let request;const {module}=fixture({databaseList:async value=>(request=value,{page:value.page,limit:value.limit,total:0,totalPages:0,summary:{},results:[]})});await module.service.list({page:'0',limit:'500'});assert.equal(request.page,1);assert.equal(request.limit,100);});
test('call list source filter runs across full rows before slicing page',async()=>{const {module}=fixture();const result=await module.service.list({page:1,limit:10,source:'Google'});assert.equal(result.total,1);assert.equal(result.results[0].leadSource,'Google');assert.equal(result.summary.total,2);});
test('CSV export requires a date range before opening stream',async()=>{const {module}=fixture();await assert.rejects(module.service.exportCsv({},{}),e=>e.status===400);});
test('CSV export passes normalized filters to streaming repository',async()=>{const value=fixture();const response={};await value.module.service.exportCsv({date:'2026-09-20',agentId:' test_in '},response);assert.equal(value.seen.filters.agentId,'TEST_IN');assert.equal(value.seen.res,response);});
